### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Crysiz2631** [MehdiRtal/MicrosoftRewardsBot#11]
Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1156, in farmer
    browser = browserSetup(False, PC_USER_AGENT)
  File "MicrosoftRewardsBot.py", line 71, in browserSetup
    chrome_browser_obj = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
TypeError: __init__() got an unexpected keyword argument 'service'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "MicrosoftRewardsBot.py", line 1281, in <module>
    main()
  File "MicrosoftRewardsBot.py", line 1271, in main
    farmer()
  File "MicrosoftRewardsBot.py", line 1236, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment

HOW TO FIX??

**Comment by MehdiRtal** [comment]
Is there any way to reproduce the bug?
