### ISSUE TITLE
Github Workflow: Multiple Accounts

### ISSUE THREAD

**Issue by DerMuffin** [MehdiRtal/MicrosoftRewardsBot#12]
Can you run multiple Accounts with Github Workflow?

Like email1:password1,email2:password2... ?

Or how to fill this secret right for multiple accounts?

Thannks!

**Comment by DerMuffin** [comment]
********************Account1********************
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[ERROR] Time out raised.

********************Account1********************
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[ERROR] Time out raised.

**Comment by MehdiRtal** [comment]
Yes you can do as the following :
email1:password1
email2:password2

**Comment by mgrimace** [comment]
> Yes you can do as the following :
> email1:password1
> email2:password2

When I enter two accounts using this syntax in GitHub workflow, the deployment fails with error code 1. Works with one account though. I entered the second account using the syntax above as email1:password1 line 1, then email2:password2 as line 2. It looks like when adding the second account, the --headless argument is pushed to another line and ignored during deployment

**Comment by mgrimace** [comment]
<img width="1028" alt="Screen Shot 2022-09-15 at 2 28 17 PM" src="https://user-images.githubusercontent.com/55518507/190481764-528252d9-04cc-4b28-b6e7-1a292adacaa1.png">
Here's a quick screenshot to show what I mean when I enter the second account

**Comment by MehdiRtal** [comment]
Can you try with a space in between as : email1:password1 email2:password2

**Comment by mgrimace** [comment]
> Can you try with a space in between as : email1:password1 email2:password2

Tried it, line 15 which normally shows `[INFO] accounts : [***]` now shows `[INFO] accounts : ['email1@outlook.com:', 'password1', 'email2@outlook.com:password2']` <--- with the actual values that I removed here for security

**Comment by MehdiRtal** [comment]
Alright I'll have a fix for that soon, thanks for sharing.

**Comment by DerMuffin** [comment]
> Alright I'll have a fix for that soon, thanks for sharing.

Thanks! You can close my newly opened Issue. Its duplicate.

**Comment by DerMuffin** [comment]
> Alright I'll have a fix for that soon, thanks for sharing.

Any ETA? Would be great to use it

**Comment by mgrimace** [comment]
> I believe it should work now, can you try it in this format:
> email1:password1 email2:password2

Confirmed working with two accounts. `email1:password1 email2:password` with a single space between them.

**Comment by mgrimace** [comment]
@MehdiRtal two accounts working, but adding a second account outputs _both accounts and passwords in plaintext_ on line 18 [info] of the deploy logs. Adding the `--privacy` arg does not fix. Caution to anyone testing.

**Comment by MehdiRtal** [comment]
I will fix that, thanks for sharing.

**Comment by DerMuffin** [comment]
> I will fix that, thanks for sharing. Edit: I've added the fix.

Thanks for that. But it seems something dont work after that.

Run python MicrosoftRewardsBot.py --accounts *** --headless --fast --privacy
sh: 1: color: not found
Traceback (most recent call last):
  File "/home/runner/work/MicrosoftRewardsBot/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line [12](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104603129/jobs/5029266562#step:6:13)90, in <module>
    main()
  File "/home/runner/work/MicrosoftRewardsBot/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 1255, in main
    ARGS = argumentParser()
  File "/home/runner/work/MicrosoftRewardsBot/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 1034, in argumentParser
    if len(sys.argv) > 1 and not ARGS.privacy:
NameError: name 'ARGS' is not defined
Error: Process completed with exit code 1.

**Comment by MehdiRtal** [comment]
It should be fixed now.

**Comment by DerMuffin** [comment]
Can confirm: Script now runs full to the end.

BUT: When i login into the Accounts in look into the Dashboard. Nothing was collected :(

**Comment by MehdiRtal** [comment]
Can u send me the "Run Script" step logs?

**Comment by DerMuffin** [comment]
Run python MicrosoftRewardsBot.py --accounts *** --headless --fast --privacy
sh: 1: color: not found

[LOGS] "logs.txt" file not found.
[LOGS] "logs.txt" created.


[WDM] - Downloading:   0%|          | 0.00/6.98M [00:00<?, ?B/s]
[WDM] - Downloading: 100%|██████████| 6.98M/6.98M [00:00<00:00, 138MB/s]
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 7638 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/33
[BING] 2/33
[BING] 3/33
[BING] 4/33
[BING] 5/33
[BING] 6/33
[BING] 7/33
[BING] 8/33
[BING] 9/33
[BING] 10/33
[BING] [11](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:12)/33
[BING] [12](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:13)/33
[BING] [13](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:14)/33
[BING] [14](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:15)/33
[BING] [15](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:16)/33
[BING] [16](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:17)/33
[BING] [17](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:18)/33
[BING] [18](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:19)/33
[BING] [19](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:20)/33
[BING] [20](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:21)/33
[BING] [21](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:22)/33
[BING] [22](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:23)/33
[BING] [23](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:24)/33
[BING] [24](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:25)/33
[BING] [25](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:26)/33
[BING] [26](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:27)/33
[BING] 27/33
[BING] 28/33
[BING] 29/33
[BING] 30/33
[BING] 31/33
[BING] 32/33
[BING] 33/33
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 310 points today !
[POINTS] You are now at 7948 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 6954 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/33
[BING] 2/33
[BING] 3/33
[BING] 4/33
[BING] 5/33
[BING] 6/33
[BING] 7/33
[BING] 8/33
[BING] 9/33
[BING] 10/33
[BING] 11/33
[BING] 12/33
[BING] 13/33
[BING] 14/33
[BING] 15/33
[BING] 16/33
[BING] 17/33
[BING] 18/33
[BING] 19/33
[BING] 20/33
[BING] 21/33
[BING] 22/33
[BING] 23/33
[BING] 24/33
[BING] 25/33
[BING] 26/33
[BING] [27](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:28)/33
[BING] [28](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:29)/33
[BING] [29](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:30)/33
[BING] 30/33
[BING] 31/33
[BING] 32/33
[BING] 33/33
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 310 points today !
[POINTS] You are now at 7264 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 6845 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/33
[BING] 2/33
[BING] 3/33
[BING] 4/33
[BING] 5/33
[BING] 6/33
[BING] 7/33
[BING] 8/33
[BING] 9/33
[BING] 10/33
[BING] 11/33
[BING] 12/33
[BING] 13/33
[BING] 14/33
[BING] 15/33
[BING] 16/33
[BING] 17/33
[BING] 18/33
[BING] 19/33
[BING] 20/33
[BING] 21/33
[BING] 22/33
[BING] 23/33
[BING] 24/33
[BING] 25/33
[BING] 26/33
[BING] 27/33
[BING] 28/33
[BING] 29/33
[BING] [30](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:31)/33
[BING] [31](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:32)/33
[BING] 32/33
[BING] 33/33
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 310 points today !
[POINTS] You are now at 7155 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 7324 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/34
[BING] 2/34
[BING] 3/34
[BING] 4/34
[BING] 5/34
[BING] 6/34
[BING] 7/34
[BING] 8/34
[BING] 9/34
[BING] 10/34
[BING] 11/34
[BING] 12/34
[BING] 13/34
[BING] 14/34
[BING] 15/34
[BING] 16/34
[BING] 17/34
[BING] 18/34
[BING] 19/34
[BING] 20/34
[BING] 21/34
[BING] 22/34
[BING] 23/34
[BING] 24/34
[BING] 25/34
[BING] 26/34
[BING] 27/34
[BING] 28/34
[BING] 29/34
[BING] 30/34
[BING] 31/34
[BING] [32](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:33)/34
[BING] [33](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:34)/34
[BING] 34/34
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Please complete the Security Check on XYZ
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 300 points today !
[POINTS] You are now at 7624 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 6748 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[BING] Starting Desktop and Edge Bing searches...
[BING] 1/33
[BING] 2/33
[BING] 3/33
[BING] 4/33
[BING] 5/33
[BING] 6/33
[BING] 7/33
[BING] 8/33
[BING] 9/33
[BING] 10/33
[BING] 11/33
[BING] 12/33
[BING] 13/33
[BING] 14/33
[BING] 15/33
[BING] 16/33
[BING] 17/33
[BING] 18/33
[BING] 19/33
[BING] 20/33
[BING] 21/33
[BING] 22/33
[BING] 23/33
[BING] 24/33
[BING] 25/33
[BING] 26/33
[BING] 27/33
[BING] 28/33
[BING] 29/33
[BING] 30/33
[BING] 31/33
[BING] 32/33
[BING] 33/33
[BING] Finished Desktop and Edge Bing searches !
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[BING] Starting Mobile Bing searches...
[BING] 1/20
[BING] 2/20
[BING] 3/20
[BING] 4/20
[BING] 5/20
[BING] 6/20
[BING] 7/20
[BING] 8/20
[BING] 9/20
[BING] 10/20
[BING] 11/20
[BING] 12/20
[BING] 13/20
[BING] 14/20
[BING] 15/20
[BING] 16/20
[BING] 17/20
[BING] 18/20
[BING] 19/20
[BING] 20/20
[BING] Finished Mobile Bing searches !
[POINTS] You have earned 310 points today !
[POINTS] You are now at 70[58](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3104671508/jobs/5029411992#step:6:59) points !

**Comment by DerMuffin** [comment]
Rerun:

Run python MicrosoftRewardsBot.py --accounts *** --headless --fast --privacy
sh: 1: color: not found

[LOGS] "logs.txt" file not found.
[LOGS] "logs.txt" created.


[WDM] - Downloading:   0%|          | 0.00/6.98M [00:00<?, ?B/s]
[WDM] - Downloading:  66%|██████▋   | 4.63M/6.98M [00:00<00:00, 48.5MB/s]
[WDM] - Downloading: 100%|██████████| 6.98M/6.98M [00:00<00:00, 57.6MB/s]
[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 79[48](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3106654849/jobs/5033806733#step:6:49) points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[POINTS] You have earned 0 points today !
[POINTS] You are now at 7948 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 7264 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[POINTS] You have earned 0 points today !
[POINTS] You are now at 7264 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 71[55](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3106654849/jobs/5033806733#step:6:56) points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[POINTS] You have earned 0 points today !
[POINTS] You are now at 7155 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 7624 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[POINTS] You have earned 0 points today !
[POINTS] You are now at 7624 points !

[LOGIN] Logging-in...
[LOGIN] Writing email...
[LOGIN] Writing password...
[LOGIN] Passing security checks...
[LOGIN] Logged-in !
[LOGIN] Logging into Microsoft Rewards...
[LOGIN] Ensuring login on Bing...
[LOGIN] Logged-in successfully !
[POINTS] You have 7058 points on your account !
[DAILY SET] Trying to complete the Daily Set...
[DAILY SET] Completed the Daily Set successfully !
[PUNCH CARDS] Trying to complete the Punch Cards...
[PUNCH CARDS] Completed the Punch Cards successfully !
[MORE PROMO] Trying to complete More Promotions...
[MORE PROMO] Completed More Promotions successfully !
[POINTS] You have earned 0 points today !
[POINTS] You are now at 7058 points !

The script took : 00:09:[56](https://github.com/DerMuffin/MicrosoftRewardsBot/actions/runs/3106654849/jobs/5033806733#step:6:57)


Seems like everthing is fine. But Dashboard still no changes

**Comment by DerMuffin** [comment]
> > I believe it should work now, can you try it in this format:
> > email1:password1 email2:password2
> 
> Confirmed working with two accounts. `email1:password1 email2:password` with a single space between them.

Can you login into rewards dashboard and confirm that all points get collected?

**Comment by MehdiRtal** [comment]
As I can see the script already shows that you earned 0 points, meaning that you claimed all for today.

**Comment by DerMuffin** [comment]
> As I can see the script already shows that you earned 0 points, meaning that you claimed all for today.

Correct. The first run run all through the searches and cards. The second run already know that everthing is connected

![image](https://user-images.githubusercontent.com/53898156/191822742-749b62fb-06ff-4c42-80f3-9ab3f42c4846.png)
![image](https://user-images.githubusercontent.com/53898156/191822836-87d26c79-6c00-4c72-91db-99a8252ce625.png)


Thats how my dashboard looks

**Comment by MehdiRtal** [comment]
The way microsoft rewards work is that from every location you get different tasks.

**Comment by MehdiRtal** [comment]
So I believe that if you use a USA proxy you will find everything done.

**Comment by MehdiRtal** [comment]
Actually I'm working on a new feature which might increase daily points to over 1000+ using proxies.

**Comment by mgrimace** [comment]
> So I believe that if you use a USA proxy you will find everything done.

Is it based on where github is deploying the script from? I'm in Canada and as far as I can tell the script is running from the US for me. Looks like my searches are complete, but I can't be certain it was this one since I also use a different second script that runs an hour later as a cron job as a backup. Between both I seem to catch everything.

**Comment by DerMuffin** [comment]
> So I believe that if you use a USA proxy you will find everything done.

Ohh okay. That kinda make sense. Thanks for that hint!

**Comment by DerMuffin** [comment]
Any Idea how to fix "No Internet connection" error? Sometimes this pop up in the middle of running the script and github forced after 10 Hours run a exit.

**Comment by MehdiRtal** [comment]
You can remove the check manually from the code but I think that it shows for a reason, does it occur on every run?

**Comment by DerMuffin** [comment]
> You can remove the check manually from the code but I think that it shows for a reason, does it occur on every run?

No. Not every run. Its kinda random. Only when i run it with workflow.

You can check my latest runs. Then you see what i mean.

When i run it on my local computer this never happens to me

**Comment by DerMuffin** [comment]
Seems like the Accounts got locked sometimes. Would it be possible to skip the account that locked and farm the next one? @MehdiRtal

**Comment by MehdiRtal** [comment]
Locked? Meaning suspended?

**Comment by DerMuffin** [comment]
@MehdiRtal Temporary disabled. I need to login into the account and type in a code that i receive via SMS.

Testing now if it works again.

**Comment by MehdiRtal** [comment]
Yes I believe this happens because they all use the same IP.
I will add a proxy feature later to avoid this.
For now it would be better if you split the accounts into multiple forks.

**Comment by Millennium99** [comment]
Thats exactly what im testing since a few days. But as i see.... happend too.
Think the problem is the Github Proxy in general. Maybe not the best idea to farm this Points on a microsoft plattform^^

Looking forward to the proxy feature! Thanks!

BTW: is it somehow possible to buy you a coffee?

**Comment by DerMuffin** [comment]
Thats exactly what im testing since a few days. But as i see.... happend too.
Think the problem is the Github Proxy in general. Maybe not the best idea to farm this Points on a microsoft plattform^^

Looking forward to the proxy feature! Thanks!

BTW: is it somehow possible to buy you a coffee?

**Comment by DerMuffin** [comment]
Seems like that i got it fixed. When the Account got locked out. Just sign in manually and unlock the account with a sms code.

Just working fine now. Ill update you on the topic.

**Comment by MehdiRtal** [comment]
I'm a bit busy these days so I believe it will take some time. 
As for the donations you can check my profile.

**Comment by MehdiRtal** [comment]
Also it would be better if you open a new issues so new users can know.
Thanks.
