### ISSUE TITLE
Supports only Linux64

### ISSUE THREAD

**Issue by TheRedM** [MehdiRtal/MicrosoftRewardsBot#24]
It would be great to see chromium support (chromium webdriver), that way we can run it on a wider range of machines.

**Comment by MehdiRtal** [comment]
This isn't a priority feature for now.

**Comment by SylveonBottle** [comment]
Rip, I wanted to run this on my pi but google-chrome doesn't have an arm64 version.

**Comment by MehdiRtal** [comment]
Is chromium supported?

**Comment by SylveonBottle** [comment]
Doesn't seem like it. I constantly get crashes when attempting to run the code on my pi, but it works just fine on my ubuntu vm with the exact same setup.


The exact error is
```
Traceback (most recent call last):
  File "/home/ubuntu/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 1211, in farmer
    browser = browserSetup(False, PC_USER_AGENT, random.choice(ARGS.proxies) if ARGS.proxies else None)
  File "/home/ubuntu/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 77, in browserSetup
    chrome_browser_obj = webdriver.Chrome(service=Service(ChromeDriverManager().install()), options=options)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    super().__init__(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 103, in __init__
    self.service.start()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 91, in start
    self._start_process(self.path)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/selenium/webdriver/common/service.py", line 189, in _start_process
    self.process = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 8] Exec format error: '/home/ubuntu/.wdm/drivers/chromedriver/linux64/107.0.5304/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 1309, in <module>
    main()
  File "/home/ubuntu/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 1299, in main
    farmer()
  File "/home/ubuntu/MicrosoftRewardsBot/MicrosoftRewardsBot.py", line 1273, in farmer
    browser.quit()
UnboundLocalError: local variable 'browser' referenced before assignment
```


This is with chromium, python 3.11 (same as github uses), and all the requirements met outside of google-chrome.
Remember, this program runs perfectly fine on my ubuntu vm. The only difference is that the ubuntu vm runs with google-chrome, but google-chrome doesn't have an arm64 version so I can't install it on my pi.

**Comment by MehdiRtal** [comment]
Try the version I have on my [dev](https://github.com/MehdiRtal/MicrosoftRewardsBot/tree/dev) branch.

**Comment by SylveonBottle** [comment]
> Try the version I have on my [dev](https://github.com/MehdiRtal/MicrosoftRewardsBot/tree/dev) branch.

https://hastebin.com/pesumeruyu.apache

**Comment by MehdiRtal** [comment]
I believe you should manually downloa chrome webdriver for arm64 and include it in the script.

**Comment by MehdiRtal** [comment]
Since i'm using webdriver_manager; I think they only support x64 / x86.

**Comment by SylveonBottle** [comment]
> I believe you should manually downloa chrome webdriver for arm64 and include it in the script.

Both chromium-browser and chromium-chromedriver are already the newest version (1:85.0.4183.83-0ubuntu2). Should I manually install both then?
And what do you mean by "include it in the script"?
